### ISSUE TITLE
AttributeError:  module 'singer_sdk.typing' has no attribute 'ListType'

### ISSUE THREAD

**Issue by keithhackbarth** [rawwar/tap-greenhouse#1]
When trying to clone and run this tap from the command line - I get the error.

```
tap_greenhouse/schemas/close_reasons.py", line 4, in <module>
    schema = th.ListType(
             ^^^^^^^^^^^
AttributeError: module 'singer_sdk.typing' has no attribute 'ListType'. Did you mean: 'TimeType'?
```

At first, I thought my dependencies might have gotten invalidated but looking at singer_sdk I don't see any evidence of ListType ever existing in the repository. If I switch to ArrayType and re-run, I then get

```
tap_greenhouse/schemas/custom_fields.py", line 45, in <module>
    th.Property(
TypeError: Property.__init__() got an unexpected keyword argument 'nullable'
```

**Comment by rawwar** [comment]
Thanks for raising the issue. I will fix it today.

**Comment by rawwar** [comment]
@keithhackbarth , Can you try now? I've fixed issues and tested it locally

**Comment by keithhackbarth** [comment]
Works great. Thank you!
