### ISSUE TITLE
Mismatch Between JSON Schema and API Data Structure for rejection_reason Field

### ISSUE THREAD

**Issue by lanathaniel** [rawwar/tap-greenhouse#3]
There seems to be a mismatch between the JSON schema defined in the ApplicationsStream and ListRejectionReasonStream classes and the actual data structure returned from the API for the rejection_reason field.

Steps to reproduce:

Run the extraction process with the applications stream.
The process fails with a ValidationError.
The validation error I'm encountering is:

`jsonschema.exceptions.ValidationError: {'type': {'name': 'We rejected them', 'id': 4000000101}, 'name': 'Duplicate', 'id': 4000005101} is not of type 'string', 'null'`

it seems like the rejection_reason field in the data is a dictionary with keys 'type', 'name', and 'id', instead of a string or null as defined in the JSON schema.

Here's an example of the data structure for the rejection_reason field as returned from the API:

```
"rejection_reason": {
    "type": {
        "name": "We rejected them",
        "id": 4000000101
    },
    "name": "Future pipeline for different role",
    "id": 4000997101
}
```

**Comment by rawwar** [comment]
Thanks for reporting the issue. Looking into it

**Comment by rawwar** [comment]
@lanathaniel , fixed it. Please check now.

**Comment by rawwar** [comment]
closing it
